{
  "hash": "43ccb29fff245c726be91d6d140697b9",
  "result": {
    "engine": "jupyter",
    "markdown": "---\nresources:\n  - datos/cap01_series.csv\n---\n\n# De la evidencia a la producción {#sec-produccion}\n\n\n\nLos veinticuatro capítulos anteriores midieron una sola cosa: **cuánto se equivoca un método**.\nEs la pregunta correcta mientras el pronóstico es un número en un cuaderno. Cuando alguien más lo\nusa —para pedir inventario, para dimensionar un turno, para decidir un precio— aparecen tres\npreguntas que ningún promedio de sMAPE contesta.\n\n1. **¿Qué pasa cuando el método falla?** No en promedio: en el peor caso que va a ver el usuario.\n2. **¿Qué hay que guardar y cuánto pesa?** Un modelo por serie y un modelo por serie y por paso son\n   dos sistemas distintos.\n3. **¿Cuánto tarda?** Una característica que cuesta diecinueve segundos no existe en una interfaz.\n\nNinguna de las tres es nueva como preocupación: @sculley2015 las llamó deuda técnica del\naprendizaje automático y @paleyes2022 las relevaron caso por caso. Lo que suele faltar es medirlas\nsobre los datos propios, y eso es lo que hace este capítulo, sobre las mismas series del libro. Al\nfinal está lo que la fase siguiente de este proyecto —una aplicación de pronóstico— tiene que\nresolver y lo que ya tiene resuelto.\n\nQue la precisión no alcanza para decidir qué método usar tampoco es una idea de este libro:\n@januschowski2020 proponen clasificar los métodos por un conjunto de criterios donde la exactitud es\nuno entre varios, junto con el costo de cómputo, la interpretabilidad y qué tan fácil es\nmantenerlos.\n\n## Lo que el promedio esconde {#sec-cola-produccion}\n\nUn promedio de error es un contrato con quien mira la tabla, no con quien mira un pronóstico. La\ndistribución del error por serie lo dice mejor que cualquier argumento.\n\n::: {#tbl-cola .cell tbl-cap='Distribución del sMAPE por serie de los tres métodos que los metadatos guardan, sobre las 99.935 series de M4. En las frecuencias con m = 1 el naive estacional es el naive.' execution_count=2}\n``` {.python .cell-code}\nM = metadatos()\nsnaive_smape = (M[\"error_snaive_smape\"].astype(float)\n                .fillna(M[\"error_naive_smape\"].astype(float)))\nERRORES = {\n    \"naive\": M[\"error_naive_smape\"].astype(float).to_numpy(),\n    \"naive estacional\": snaive_smape.to_numpy(),\n    \"ARIMA\": M[\"error_arima_smape\"].astype(float).to_numpy(),\n}\n\nfilas = []\nfor nombre, x in ERRORES.items():\n    orden = np.sort(x)\n    peor1 = orden[int(0.99 * len(orden)):]\n    filas.append({\n        \"método\": nombre,\n        \"media\": 100 * x.mean(),\n        \"mediana\": 100 * np.median(x),\n        \"p90\": 100 * np.quantile(x, 0.90),\n        \"p99\": 100 * np.quantile(x, 0.99),\n        \"máximo\": 100 * x.max(),\n        \"% del error total en el peor 1 %\": 100 * peor1.sum() / x.sum(),\n    })\nCOLA = pd.DataFrame(filas).set_index(\"método\")\nCOLA.round(1)\n```\n\n::: {.cell-output .cell-output-display execution_count=2}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>media</th>\n      <th>mediana</th>\n      <th>p90</th>\n      <th>p99</th>\n      <th>máximo</th>\n      <th>% del error total en el peor 1 %</th>\n    </tr>\n    <tr>\n      <th>método</th>\n      <th></th>\n      <th></th>\n      <th></th>\n      <th></th>\n      <th></th>\n      <th></th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>naive</th>\n      <td>14.2</td>\n      <td>8.3</td>\n      <td>34.2</td>\n      <td>79.6</td>\n      <td>190.0</td>\n      <td>7.1</td>\n    </tr>\n    <tr>\n      <th>naive estacional</th>\n      <td>14.7</td>\n      <td>9.1</td>\n      <td>34.6</td>\n      <td>76.7</td>\n      <td>188.6</td>\n      <td>6.6</td>\n    </tr>\n    <tr>\n      <th>ARIMA</th>\n      <td>13.2</td>\n      <td>7.4</td>\n      <td>32.5</td>\n      <td>75.3</td>\n      <td>200.0</td>\n      <td>7.7</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\nLa mediana de los tres está debajo de 9 % y el p99 arriba de\n75 %: un factor de nueve entre la serie típica y la serie mala.\nEl máximo de ARIMA es 200, que es el techo del sMAPE\n—el @sec-evaluacion mostró que la métrica se satura en 200— y significa que en esas series el\npronóstico no tiene ninguna relación con lo que pasó.\n\nEso ya es incómodo. Lo que sigue es peor, porque no habla del error absoluto sino de lo que se\npierde por elegir mal.\n\n::: {#tbl-hueco-cola .cell tbl-cap='El hueco entre ARIMA y el mejor de los tres métodos en cada serie, y de dónde sale ese hueco.' execution_count=3}\n``` {.python .cell-code}\nE = np.column_stack(list(ERRORES.values()))\nmejor = E.min(axis=1)\nhueco = E[:, 2] - mejor\norden = np.sort(hueco)\nfilas = []\nfor q, etiqueta in [(0.99, \"el peor 1 %\"), (0.95, \"el peor 5 %\"), (0.90, \"el peor 10 %\")]:\n    corte = orden[int(q * len(orden)):]\n    filas.append({\n        \"subconjunto de series\": etiqueta,\n        \"series\": len(corte),\n        \"% del hueco total\": 100 * corte.sum() / hueco.sum(),\n    })\nHUECO = pd.DataFrame(filas).set_index(\"subconjunto de series\")\nHUECO.round(1)\n```\n\n::: {.cell-output .cell-output-display execution_count=3}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>series</th>\n      <th>% del hueco total</th>\n    </tr>\n    <tr>\n      <th>subconjunto de series</th>\n      <th></th>\n      <th></th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>el peor 1 %</th>\n      <td>1000</td>\n      <td>22.0</td>\n    </tr>\n    <tr>\n      <th>el peor 5 %</th>\n      <td>4997</td>\n      <td>53.1</td>\n    </tr>\n    <tr>\n      <th>el peor 10 %</th>\n      <td>9994</td>\n      <td>71.7</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\nEl 22 % de todo lo que se pierde por\nusar ARIMA en vez del mejor método disponible está en el 1 % de las series, y el\n53 % en el 5 %. En\n7\\,5 % de las series —\n7\\.510 en total— ARIMA da más del\ndoble del error del mejor de los tres.\n\n::: {.callout-important}\n## La media promete algo que el usuario no recibe\n\nQuien lee \"sMAPE medio 13,2 %\" entiende \"mis pronósticos van a errar alrededor del 13 %\". Lo que la\ntabla dice es otra cosa: la mitad de las series erran menos del\n7 %, y una de cada cien erra más del\n75 %.\n\nEn una tabla comparativa la media alcanza. En una aplicación, cada serie es un usuario distinto, y\nel usuario que cayó en el p99 no tiene con qué saberlo. **Es la razón por la que un sistema en\nproducción necesita defensas que un experimento no necesita**, y las tres secciones que siguen son\nesas defensas.\n:::\n\n## La cota de cordura {#sec-cota-cordura}\n\nLa defensa más barata no usa ningún modelo: usa lo que la serie histórica ya dice sobre qué valores\nson posibles. Si una serie de unidades vendidas nunca fue negativa, un pronóstico negativo está mal\nsin necesidad de esperar el futuro.\n\nSea $\\hat y_{t+k}$ el pronóstico del paso $k$, y sean $y_{\\min}$ e $y_{\\max}$ el mínimo y el máximo\ndel histórico, con rango $r = y_{\\max} - y_{\\min}$. La **cota de cordura** con margen $c \\ge 0$ es\n\n$$\n\\tilde y_{t+k} = \\min\\!\\Big(\\max\\big(\\hat y_{t+k},\\; L\\big),\\; U\\Big),\n\\qquad L = y_{\\min} - c\\,r, \\qquad U = y_{\\max} + c\\,r,\n$$ {#eq-cota}\n\ny si la cantidad no admite valores negativos, $L$ se reemplaza por $\\max(L, 0)$. Con $c = 0$ el\npronóstico no puede salir del rango observado; con $c \\to \\infty$ la cota no hace nada.\n\nPara medirla hace falta un método que se equivoque de manera espectacular. Holt sirve: extrapola\nuna tendencia lineal sin amortiguar, y el @sec-suavizado ya mostró qué pasa cuando la tendencia\nestimada apunta en la dirección equivocada.\n\n::: {#tbl-cota .cell tbl-cap='La @eq-cota aplicada al pronóstico de Holt sobre las series del catálogo, con distintos márgenes.' execution_count=4}\n``` {.python .cell-code}\nfrom statsmodels.tsa.holtwinters import Holt\n\nPRON_HOLT = {}\nfor s in SERIES:\n    y = s.entrenamiento.to_numpy(float)\n    ajuste = Holt(y, initialization_method=\"estimated\").fit()\n    PRON_HOLT[s.id] = np.asarray(ajuste.forecast(s.horizonte), float)\n\n\ndef cota_por_rango(c):\n    \"\"\"Devuelve una función que da (L, U) según la @eq-cota.\"\"\"\n    def cota(serie, y):\n        if np.isinf(c):\n            return -np.inf, np.inf\n        bajo, alto = y.min(), y.max()\n        rango = alto - bajo\n        L = bajo - c * rango\n        return (max(L, 0.0) if (y > 0).all() else L), alto + c * rango\n    return cota\n\n\ndef evaluar(cota):\n    smapes, mases, recortados = [], [], 0\n    for s in SERIES:\n        y = s.entrenamiento.to_numpy(float)\n        real = s.prueba.to_numpy(float)\n        pron = PRON_HOLT[s.id]\n        L, U = cota(s, y)\n        recortados += int(((pron < L) | (pron > U)).sum())\n        acotado = np.clip(pron, L, U)\n        smapes.append(smape(real, acotado))\n        mases.append(mase(real, acotado, y, max(s.periodo_estacional, 1)))\n    return {\"pasos recortados\": recortados, \"sMAPE medio\": np.mean(smapes),\n            \"MASE medio\": np.mean(mases), \"MASE máximo\": max(mases)}\n\n\nfilas = []\nfor c, etiqueta in [(np.inf, \"sin cota\"), (1.0, \"c = 1\"), (0.5, \"c = 0,5\"),\n                    (0.25, \"c = 0,25\"), (0.0, \"c = 0 (rango observado)\")]:\n    filas.append({\"margen\": etiqueta, **evaluar(cota_por_rango(c))})\nCOTA = pd.DataFrame(filas).set_index(\"margen\")\nCOTA.round({\"pasos recortados\": 0, \"sMAPE medio\": 2, \"MASE medio\": 2, \"MASE máximo\": 1})\n```\n\n::: {.cell-output .cell-output-display execution_count=4}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>pasos recortados</th>\n      <th>sMAPE medio</th>\n      <th>MASE medio</th>\n      <th>MASE máximo</th>\n    </tr>\n    <tr>\n      <th>margen</th>\n      <th></th>\n      <th></th>\n      <th></th>\n      <th></th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>sin cota</th>\n      <td>0</td>\n      <td>47.10</td>\n      <td>35.72</td>\n      <td>356.2</td>\n    </tr>\n    <tr>\n      <th>c = 1</th>\n      <td>160</td>\n      <td>46.22</td>\n      <td>25.24</td>\n      <td>274.4</td>\n    </tr>\n    <tr>\n      <th>c = 0,5</th>\n      <td>176</td>\n      <td>44.31</td>\n      <td>23.16</td>\n      <td>205.7</td>\n    </tr>\n    <tr>\n      <th>c = 0,25</th>\n      <td>205</td>\n      <td>38.79</td>\n      <td>19.79</td>\n      <td>163.6</td>\n    </tr>\n    <tr>\n      <th>c = 0 (rango observado)</th>\n      <td>298</td>\n      <td>31.40</td>\n      <td>15.72</td>\n      <td>116.2</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\nCuanto más apretada la cota, mejor. El MASE medio baja de\n35\\,7 a\n15\\,7, y el peor caso del catálogo\n—una serie donde Holt erra 356 veces lo que\nerraría el naive— baja a 116.\n\nEl sMAPE también mejora, pero mucho menos, y la razón importa: **el sMAPE no distingue un pronóstico\nabsurdo de uno malo.** Cuando el pronóstico se va muy lejos del valor real, el cociente\n$2|\\hat y - y| / (|y| + |\\hat y|)$ tiende a 2 y ahí se queda, sea el pronóstico el doble de lo\nrazonable o mil veces. La @sec-h366 encontró el mismo efecto en la tesis, y es el argumento más\nfuerte del libro a favor de reportar siempre las dos métricas.\n\n::: {.callout-warning}\n## Un piso en cero no es una cota de cordura\n\nSobre la serie con quiebre de nivel del catálogo, Holt pronostica valores de hasta\n\\-1\\.980 en una serie cuyo histórico va de\n356 a\n3\\.716.\n\nRecortar en cero deja el pronóstico en cero, y el sMAPE de un cero contra un valor positivo es 200:\nel máximo posible. Recortar al mínimo histórico, en cambio, baja el sMAPE de esa serie de\n179 a\n80.\n\n**El piso tiene que ser un valor plausible, no el primer valor legal.** Cero es legal y casi nunca\nes plausible.\n:::\n\nAhora la parte incómoda. La cota con $c = 0$ mejora el agregado, pero no mejora todas las series.\n\n::: {#tbl-cota-danio .cell tbl-cap='Efecto de la cota con c = 0 serie por serie: cuántas mejoran, cuántas empeoran y cuánto.' execution_count=5}\n``` {.python .cell-code}\ndef por_serie(cota):\n    filas = []\n    for s in SERIES:\n        y = s.entrenamiento.to_numpy(float)\n        real = s.prueba.to_numpy(float)\n        pron = PRON_HOLT[s.id]\n        L, U = cota(s, y)\n        filas.append({\"serie\": s.id, \"fenómeno\": s.fenomeno,\n                      \"diferencia\": smape(real, np.clip(pron, L, U)) - smape(real, pron)})\n    return pd.DataFrame(filas)\n\n\ndef resumen(d, etiqueta):\n    return {\"regla\": etiqueta,\n            \"series que mejoran\": int((d[\"diferencia\"] < -0.01).sum()),\n            \"series que empeoran\": int((d[\"diferencia\"] > 0.01).sum()),\n            \"series sin cambio\": int((d[\"diferencia\"].abs() <= 0.01).sum()),\n            \"peor daño (puntos de sMAPE)\": d[\"diferencia\"].max(),\n            \"mejor ganancia\": d[\"diferencia\"].min()}\n\n\nDURA = por_serie(cota_por_rango(0.0))\nDURA.loc[DURA[\"diferencia\"].abs() > 0.01].sort_values(\"diferencia\").round(2).set_index(\"serie\")\n```\n\n::: {.cell-output .cell-output-display execution_count=5}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>fenómeno</th>\n      <th>diferencia</th>\n    </tr>\n    <tr>\n      <th>serie</th>\n      <th></th>\n      <th></th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>H316</th>\n      <td>estacionalidad-multiple</td>\n      <td>-103.07</td>\n    </tr>\n    <tr>\n      <th>H242</th>\n      <td>estacionalidad-marcada</td>\n      <td>-98.87</td>\n    </tr>\n    <tr>\n      <th>M32692</th>\n      <td>quiebre-de-nivel</td>\n      <td>-98.47</td>\n    </tr>\n    <tr>\n      <th>H272</th>\n      <td>caminata-aleatoria</td>\n      <td>-97.82</td>\n    </tr>\n    <tr>\n      <th>H313</th>\n      <td>estacionalidad-multiple</td>\n      <td>-85.87</td>\n    </tr>\n    <tr>\n      <th>H317</th>\n      <td>tendencia-y-estacionalidad</td>\n      <td>-60.27</td>\n    </tr>\n    <tr>\n      <th>H282</th>\n      <td>estacionalidad-marcada</td>\n      <td>-15.54</td>\n    </tr>\n    <tr>\n      <th>Y22817</th>\n      <td>serie-corta</td>\n      <td>-0.85</td>\n    </tr>\n    <tr>\n      <th>Q23601</th>\n      <td>tendencia-y-estacionalidad</td>\n      <td>-0.12</td>\n    </tr>\n    <tr>\n      <th>D1</th>\n      <td>tendencia-limpia</td>\n      <td>0.28</td>\n    </tr>\n    <tr>\n      <th>M3007</th>\n      <td>usada-en-el-texto</td>\n      <td>0.30</td>\n    </tr>\n    <tr>\n      <th>Q1915</th>\n      <td>tendencia-limpia</td>\n      <td>2.45</td>\n    </tr>\n    <tr>\n      <th>Q5932</th>\n      <td>cobertura-de-dificultad</td>\n      <td>2.70</td>\n    </tr>\n    <tr>\n      <th>M39292</th>\n      <td>tendencia-limpia</td>\n      <td>5.65</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n::: {#cell-fig-cota .cell execution_count=6}\n``` {.python .cell-code}\ns_q = cargar(\"M32692\")\ny_q = s_q.entrenamiento.to_numpy(float)\nreal_q = s_q.prueba.to_numpy(float)\npron_q = PRON_HOLT[\"M32692\"]\nbajo_q, alto_q = y_q.min(), y_q.max()\nacotado_q = np.clip(pron_q, bajo_q, alto_q)\ncola = 60                                    # últimas observaciones que se dibujan\nfechas_tr = s_q.entrenamiento.index[-cola:]\nfechas_pr = s_q.prueba.index\n\nfig = go.Figure()\nfig.add_hrect(y0=bajo_q, y1=alto_q, fillcolor=COLORES[\"auxiliar\"], opacity=0.12,\n              line_width=0)\nfig.add_trace(go.Scatter(x=fechas_tr, y=y_q[-cola:], mode=\"lines\",\n                         name=\"histórico\",\n                         line=dict(color=COLORES[\"observado\"], width=2)))\nfig.add_trace(go.Scatter(x=fechas_pr, y=real_q, mode=\"lines+markers\",\n                         name=\"lo que pasó\",\n                         line=dict(color=COLORES[\"prueba\"], width=2),\n                         marker=dict(size=6)))\nfig.add_trace(go.Scatter(x=fechas_pr, y=pron_q, mode=\"lines+markers\",\n                         name=\"Holt sin cota\",\n                         line=dict(color=COLORES[\"auxiliar\"], width=2, dash=\"dot\"),\n                         marker=dict(size=6)))\nfig.add_trace(go.Scatter(x=fechas_pr, y=acotado_q, mode=\"lines+markers\",\n                         name=\"Holt acotado\",\n                         line=dict(color=COLORES[\"pronostico\"], width=2),\n                         marker=dict(size=6)))\nfig.add_hline(y=0, line=dict(color=COLORES[\"auxiliar\"], width=1))\nmostrar(fig, alto=430, titulo_y=\"valor de la serie\")\n```\n\n::: {#fig-cota .cell-output .cell-output-display}\n```{=html}\n<div style=\"height:430px; width:100%;\">                        <script>window.PlotlyConfig = {MathJaxConfig: 'local'};</script>\n        <script charset=\"utf-8\" src=\"https://cdn.plot.ly/plotly-3.7.0.min.js\" integrity=\"sha256-jvTGqxNp8AGWEcvNLVuKr+8j5dGe9Yw51LQkmDH+IYA=\" crossorigin=\"anonymous\"></script>                <div id=\"c6d1f5cb-823a-4cd5-8688-212d104a2a76\" class=\"plotly-graph-div\" style=\"height:100%; width:100%;\"></div>            <script>                window.PLOTLYENV=window.PLOTLYENV || {};                                if (document.getElementById(\"c6d1f5cb-823a-4cd5-8688-212d104a2a76\")) {                    Plotly.newPlot(                        \"c6d1f5cb-823a-4cd5-8688-212d104a2a76\",                        [{\"line\":{\"color\":\"#1f4e79\",\"width\":2},\"mode\":\"lines\",\"name\":\"histórico\",\"x\":[\"2010-08-01T00:00:00\",\"2010-09-01T00:00:00\",\"2010-10-01T00:00:00\",\"2010-11-01T00:00:00\",\"2010-12-01T00:00:00\",\"2011-01-01T00:00:00\",\"2011-02-01T00:00:00\",\"2011-03-01T00:00:00\",\"2011-04-01T00:00:00\",\"2011-05-01T00:00:00\",\"2011-06-01T00:00:00\",\"2011-07-01T00:00:00\",\"2011-08-01T00:00:00\",\"2011-09-01T00:00:00\",\"2011-10-01T00:00:00\",\"2011-11-01T00:00:00\",\"2011-12-01T00:00:00\",\"2012-01-01T00:00:00\",\"2012-02-01T00:00:00\",\"2012-03-01T00:00:00\",\"2012-04-01T00:00:00\",\"2012-05-01T00:00:00\",\"2012-06-01T00:00:00\",\"2012-07-01T00:00:00\",\"2012-08-01T00:00:00\",\"2012-09-01T00:00:00\",\"2012-10-01T00:00:00\",\"2012-11-01T00:00:00\",\"2012-12-01T00:00:00\",\"2013-01-01T00:00:00\",\"2013-02-01T00:00:00\",\"2013-03-01T00:00:00\",\"2013-04-01T00:00:00\",\"2013-05-01T00:00:00\",\"2013-06-01T00:00:00\",\"2013-07-01T00:00:00\",\"2013-08-01T00:00:00\",\"2013-09-01T00:00:00\",\"2013-10-01T00:00:00\",\"2013-11-01T00:00:00\",\"2013-12-01T00:00:00\",\"2014-01-01T00:00:00\",\"2014-02-01T00:00:00\",\"2014-03-01T00:00:00\",\"2014-04-01T00:00:00\",\"2014-05-01T00:00:00\",\"2014-06-01T00:00:00\",\"2014-07-01T00:00:00\",\"2014-08-01T00:00:00\",\"2014-09-01T00:00:00\",\"2014-10-01T00:00:00\",\"2014-11-01T00:00:00\",\"2014-12-01T00:00:00\",\"2015-01-01T00:00:00\",\"2015-02-01T00:00:00\",\"2015-03-01T00:00:00\",\"2015-04-01T00:00:00\",\"2015-05-01T00:00:00\",\"2015-06-01T00:00:00\",\"2015-07-01T00:00:00\"],\"y\":{\"dtype\":\"f8\",\"bdata\":\"MzMzMzNzeUAAAAAAAHB7QGZmZmZmVn9AAAAAAAA8iUAzMzMzM3+WQM3MzMzMBqVAAAAAAACZqEBmZmZmZiikQM3MzMzMX6FAmpmZmZnlkkBmZmZmZrqHQM3MzMzM\\u002fHpAzczMzMx0d0AzMzMzM7N+QAAAAAAAFIFAAAAAAAAEjEAzMzMzM5OVQAAAAAAAY6BAAAAAAAB2pECamZmZmW6hQJqZmZmZk5JAMzMzMzPhkEBmZmZmZiKDQGZmZmZm4oBAAAAAAAB4eUAAAAAAAPh5QJqZmZmZUYBAmpmZmZlnkUAAAAAAANKbQJqZmZmZ0Z9AAAAAAACspUCamZmZmdmkQM3MzMzM+KJAMzMzMzODkkAzMzMzM9eBQGZmZmZm5ntAAAAAAAAgf0DNzMzMzDx8QJqZmZmZsX9AZmZmZmZ+hkCamZmZmfWeQDMzMzMzQKRAZmZmZmbBrEDNzMzMzC+oQGZmZmZmkqRAMzMzMzMPkUCamZmZmUGEQDMzMzMzd4BAZmZmZmb+fUAzMzMzM1t9QAAAAAAAoIFAzczMzMyojUAzMzMzMw2cQM3MzMzMj6JAMzMzMzOLqUAzMzMzMwmqQAAAAAAA6KJAAAAAAAAalEDNzMzMzDyEQJqZmZmZTYBA\"},\"type\":\"scatter\"},{\"line\":{\"color\":\"#c0504d\",\"width\":2},\"marker\":{\"size\":6},\"mode\":\"lines+markers\",\"name\":\"lo que pasó\",\"x\":[\"2015-08-01T00:00:00\",\"2015-09-01T00:00:00\",\"2015-10-01T00:00:00\",\"2015-11-01T00:00:00\",\"2015-12-01T00:00:00\",\"2016-01-01T00:00:00\",\"2016-02-01T00:00:00\",\"2016-03-01T00:00:00\",\"2016-04-01T00:00:00\",\"2016-05-01T00:00:00\",\"2016-06-01T00:00:00\",\"2016-07-01T00:00:00\",\"2016-08-01T00:00:00\",\"2016-09-01T00:00:00\",\"2016-10-01T00:00:00\",\"2016-11-01T00:00:00\",\"2016-12-01T00:00:00\",\"2017-01-01T00:00:00\"],\"y\":{\"dtype\":\"f8\",\"bdata\":\"ZmZmZmY+fUCamZmZmXl9QAAAAAAA6HtAZmZmZmZejEDNzMzMzNCTQM3MzMzMUJlAZmZmZmZfp0DNzMzMzGeiQGZmZmZmYpdAAAAAAADukkAzMzMzM9uEQDMzMzMzI3pAAAAAAABgekCamZmZmdF+QDMzMzMzu35AZmZmZmbWikCamZmZmeGWQM3MzMzM7aJA\"},\"type\":\"scatter\"},{\"line\":{\"color\":\"#7f7f7f\",\"dash\":\"dot\",\"width\":2},\"marker\":{\"size\":6},\"mode\":\"lines+markers\",\"name\":\"Holt sin cota\",\"x\":[\"2015-08-01T00:00:00\",\"2015-09-01T00:00:00\",\"2015-10-01T00:00:00\",\"2015-11-01T00:00:00\",\"2015-12-01T00:00:00\",\"2016-01-01T00:00:00\",\"2016-02-01T00:00:00\",\"2016-03-01T00:00:00\",\"2016-04-01T00:00:00\",\"2016-05-01T00:00:00\",\"2016-06-01T00:00:00\",\"2016-07-01T00:00:00\",\"2016-08-01T00:00:00\",\"2016-09-01T00:00:00\",\"2016-10-01T00:00:00\",\"2016-11-01T00:00:00\",\"2016-12-01T00:00:00\",\"2017-01-01T00:00:00\"],\"y\":{\"dtype\":\"f8\",\"bdata\":\"QHtDpJI7d0AsV7\\u002f47SttQLBv71FtwVdA8J0\\u002fmwKqRcDQhpf2t7VmwBKTL6N3AHTAvGITSxOmfMAzmXt516WCwAeBbU2l+IbA3WhfIXNLi8CzUFH1QJ6PwEScoWSH+JHALpCaTu4hlMAYhJM4VUuWwAR4jCK8dJjA7muFDCOemsDYX372icecwMJTd+Dw8J7A\"},\"type\":\"scatter\"},{\"line\":{\"color\":\"#2e8b57\",\"width\":2},\"marker\":{\"size\":6},\"mode\":\"lines+markers\",\"name\":\"Holt acotado\",\"x\":[\"2015-08-01T00:00:00\",\"2015-09-01T00:00:00\",\"2015-10-01T00:00:00\",\"2015-11-01T00:00:00\",\"2015-12-01T00:00:00\",\"2016-01-01T00:00:00\",\"2016-02-01T00:00:00\",\"2016-03-01T00:00:00\",\"2016-04-01T00:00:00\",\"2016-05-01T00:00:00\",\"2016-06-01T00:00:00\",\"2016-07-01T00:00:00\",\"2016-08-01T00:00:00\",\"2016-09-01T00:00:00\",\"2016-10-01T00:00:00\",\"2016-11-01T00:00:00\",\"2016-12-01T00:00:00\",\"2017-01-01T00:00:00\"],\"y\":{\"dtype\":\"f8\",\"bdata\":\"QHtDpJI7d0AAAAAAAEh2QAAAAAAASHZAAAAAAABIdkAAAAAAAEh2QAAAAAAASHZAAAAAAABIdkAAAAAAAEh2QAAAAAAASHZAAAAAAABIdkAAAAAAAEh2QAAAAAAASHZAAAAAAABIdkAAAAAAAEh2QAAAAAAASHZAAAAAAABIdkAAAAAAAEh2QAAAAAAASHZA\"},\"type\":\"scatter\"}],                        {\"template\":{\"data\":{\"barpolar\":[{\"marker\":{\"line\":{\"color\":\"white\",\"width\":0.5},\"pattern\":{\"fillmode\":\"overlay\",\"size\":10,\"solidity\":0.2}},\"type\":\"barpolar\"}],\"bar\":[{\"error_x\":{\"color\":\"#2a3f5f\"},\"error_y\":{\"color\":\"#2a3f5f\"},\"marker\":{\"line\":{\"color\":\"white\",\"width\":0.5},\"pattern\":{\"fillmode\":\"overlay\",\"size\":10,\"solidity\":0.2}},\"type\":\"bar\"}],\"carpet\":[{\"aaxis\":{\"endlinecolor\":\"#2a3f5f\",\"gridcolor\":\"#C8D4E3\",\"linecolor\":\"#C8D4E3\",\"minorgridcolor\":\"#C8D4E3\",\"startlinecolor\":\"#2a3f5f\"},\"baxis\":{\"endlinecolor\":\"#2a3f5f\",\"gridcolor\":\"#C8D4E3\",\"linecolor\":\"#C8D4E3\",\"minorgridcolor\":\"#C8D4E3\",\"startlinecolor\":\"#2a3f5f\"},\"type\":\"carpet\"}],\"choropleth\":[{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"},\"type\":\"choropleth\"}],\"contourcarpet\":[{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"},\"type\":\"contourcarpet\"}],\"contour\":[{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"},\"colorscale\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]],\"type\":\"contour\"}],\"heatmap\":[{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"},\"colorscale\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]],\"type\":\"heatmap\"}],\"histogram2dcontour\":[{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"},\"colorscale\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]],\"type\":\"histogram2dcontour\"}],\"histogram2d\":[{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"},\"colorscale\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]],\"type\":\"histogram2d\"}],\"histogram\":[{\"marker\":{\"pattern\":{\"fillmode\":\"overlay\",\"size\":10,\"solidity\":0.2}},\"type\":\"histogram\"}],\"mesh3d\":[{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"},\"type\":\"mesh3d\"}],\"parcoords\":[{\"line\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}},\"type\":\"parcoords\"}],\"pie\":[{\"automargin\":true,\"type\":\"pie\"}],\"scatter3d\":[{\"line\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}},\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}},\"type\":\"scatter3d\"}],\"scattercarpet\":[{\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}},\"type\":\"scattercarpet\"}],\"scattergeo\":[{\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}},\"type\":\"scattergeo\"}],\"scattergl\":[{\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}},\"type\":\"scattergl\"}],\"scattermapbox\":[{\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}},\"type\":\"scattermapbox\"}],\"scattermap\":[{\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}},\"type\":\"scattermap\"}],\"scatterpolargl\":[{\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}},\"type\":\"scatterpolargl\"}],\"scatterpolar\":[{\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}},\"type\":\"scatterpolar\"}],\"scatter\":[{\"fillpattern\":{\"fillmode\":\"overlay\",\"size\":10,\"solidity\":0.2},\"type\":\"scatter\"}],\"scatterternary\":[{\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}},\"type\":\"scatterternary\"}],\"surface\":[{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"},\"colorscale\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]],\"type\":\"surface\"}],\"table\":[{\"cells\":{\"fill\":{\"color\":\"#EBF0F8\"},\"line\":{\"color\":\"white\"}},\"header\":{\"fill\":{\"color\":\"#C8D4E3\"},\"line\":{\"color\":\"white\"}},\"type\":\"table\"}]},\"layout\":{\"annotationdefaults\":{\"arrowcolor\":\"#2a3f5f\",\"arrowhead\":0,\"arrowwidth\":1},\"autotypenumbers\":\"strict\",\"coloraxis\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}},\"colorscale\":{\"diverging\":[[0,\"#8e0152\"],[0.1,\"#c51b7d\"],[0.2,\"#de77ae\"],[0.3,\"#f1b6da\"],[0.4,\"#fde0ef\"],[0.5,\"#f7f7f7\"],[0.6,\"#e6f5d0\"],[0.7,\"#b8e186\"],[0.8,\"#7fbc41\"],[0.9,\"#4d9221\"],[1,\"#276419\"]],\"sequential\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]],\"sequentialminus\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]]},\"colorway\":[\"#636efa\",\"#EF553B\",\"#00cc96\",\"#ab63fa\",\"#FFA15A\",\"#19d3f3\",\"#FF6692\",\"#B6E880\",\"#FF97FF\",\"#FECB52\"],\"font\":{\"color\":\"#2a3f5f\"},\"geo\":{\"bgcolor\":\"white\",\"lakecolor\":\"white\",\"landcolor\":\"white\",\"showlakes\":true,\"showland\":true,\"subunitcolor\":\"#C8D4E3\"},\"hoverlabel\":{\"align\":\"left\"},\"hovermode\":\"closest\",\"mapbox\":{\"style\":\"light\"},\"margin\":{\"b\":0,\"l\":0,\"r\":0,\"t\":30},\"paper_bgcolor\":\"white\",\"plot_bgcolor\":\"white\",\"polar\":{\"angularaxis\":{\"gridcolor\":\"#EBF0F8\",\"linecolor\":\"#EBF0F8\",\"ticks\":\"\"},\"bgcolor\":\"white\",\"radialaxis\":{\"gridcolor\":\"#EBF0F8\",\"linecolor\":\"#EBF0F8\",\"ticks\":\"\"}},\"scene\":{\"xaxis\":{\"backgroundcolor\":\"white\",\"gridcolor\":\"#DFE8F3\",\"gridwidth\":2,\"linecolor\":\"#EBF0F8\",\"showbackground\":true,\"ticks\":\"\",\"zerolinecolor\":\"#EBF0F8\"},\"yaxis\":{\"backgroundcolor\":\"white\",\"gridcolor\":\"#DFE8F3\",\"gridwidth\":2,\"linecolor\":\"#EBF0F8\",\"showbackground\":true,\"ticks\":\"\",\"zerolinecolor\":\"#EBF0F8\"},\"zaxis\":{\"backgroundcolor\":\"white\",\"gridcolor\":\"#DFE8F3\",\"gridwidth\":2,\"linecolor\":\"#EBF0F8\",\"showbackground\":true,\"ticks\":\"\",\"zerolinecolor\":\"#EBF0F8\"}},\"shapedefaults\":{\"line\":{\"color\":\"#2a3f5f\"}},\"ternary\":{\"aaxis\":{\"gridcolor\":\"#DFE8F3\",\"linecolor\":\"#A2B1C6\",\"ticks\":\"\"},\"baxis\":{\"gridcolor\":\"#DFE8F3\",\"linecolor\":\"#A2B1C6\",\"ticks\":\"\"},\"bgcolor\":\"white\",\"caxis\":{\"gridcolor\":\"#DFE8F3\",\"linecolor\":\"#A2B1C6\",\"ticks\":\"\"}},\"title\":{\"x\":0.05},\"xaxis\":{\"automargin\":true,\"gridcolor\":\"#EBF0F8\",\"linecolor\":\"#EBF0F8\",\"ticks\":\"\",\"title\":{\"standoff\":15},\"zerolinecolor\":\"#EBF0F8\",\"zerolinewidth\":2},\"yaxis\":{\"automargin\":true,\"gridcolor\":\"#EBF0F8\",\"linecolor\":\"#EBF0F8\",\"ticks\":\"\",\"title\":{\"standoff\":15},\"zerolinecolor\":\"#EBF0F8\",\"zerolinewidth\":2}}},\"shapes\":[{\"fillcolor\":\"#7f7f7f\",\"line\":{\"width\":0},\"opacity\":0.12,\"type\":\"rect\",\"x0\":0,\"x1\":1,\"xref\":\"x domain\",\"y0\":356.5,\"y1\":3715.7,\"yref\":\"y\"},{\"line\":{\"color\":\"#7f7f7f\",\"width\":1},\"type\":\"line\",\"x0\":0,\"x1\":1,\"xref\":\"x domain\",\"y0\":0,\"y1\":0,\"yref\":\"y\"}],\"margin\":{\"l\":10,\"r\":10,\"t\":30,\"b\":10},\"legend\":{\"orientation\":\"h\",\"y\":1.12,\"x\":0,\"title\":{}},\"font\":{\"size\":13},\"height\":430,\"hovermode\":\"x unified\",\"xaxis\":{\"title\":{}},\"yaxis\":{\"title\":{\"text\":\"valor de la serie\"}}},                        {\"displaylogo\": false, \"locale\": \"es\", \"responsive\": true, \"modeBarButtonsToRemove\": [\"select2d\", \"lasso2d\", \"autoScale2d\"], \"toImageButtonOptions\": {\"format\": \"png\", \"scale\": 2}}                    )                };            </script>        </div>\n```\n\nLa serie con quiebre de nivel del catálogo, el pronóstico de Holt y el mismo pronóstico acotado al rango observado. La banda gris es el rango del histórico.\n:::\n:::\n\n\nEn la @fig-cota se ve de dónde sale la ganancia: Holt lee la caída del último tramo como una\ntendencia y la proyecta más allá del cero, a\n\\-1\\.980 en el paso 18, sobre una serie que nunca bajó de\n356. La cota no arregla el pronóstico —sigue siendo malo—\npero lo devuelve al conjunto de los valores posibles.\n\nLas series que empeoran son todas del mismo tipo: **tendencia limpia**. Su futuro está legítimamente\narriba del máximo histórico, y la cota se lo prohíbe. Es el mismo techo de extrapolación que el\n@sec-modelos-basicos midió en los modelos de aprendizaje automático, ahora impuesto a mano.\n\nDe ahí sale la corrección. La cota no debería ser fija: debería dejar espacio proporcional a la\ntendencia que la serie ya mostró. Con $F_T$ la fuerza de la tendencia del @sec-caracteristicas y\n$\\hat\\beta$ la pendiente de una recta ajustada al histórico,\n\n$$\nL = y_{\\min} - \\delta, \\qquad U = y_{\\max} + \\delta,\n\\qquad\n\\delta =\n\\begin{cases}\n|\\hat\\beta|\\,h & \\text{si } F_T > 0{,}8 \\\\[2pt]\n0 & \\text{si no}\n\\end{cases}\n$$ {#eq-cota-condicional}\n\no sea: si la serie tiene tendencia, el pronóstico puede salir del rango observado tan rápido como\nla serie salía; si no la tiene, no puede salir.\n\n::: {#tbl-cota-condicional .cell tbl-cap='Las tres reglas comparadas. La condicional es la @eq-cota-condicional.' execution_count=7}\n``` {.python .cell-code}\ndef cota_condicional(serie, y):\n    bajo, alto = y.min(), y.max()\n    fuerza = float(CATALOGO.loc[serie.id, \"trend_strength\"])\n    if fuerza > 0.8:\n        pendiente = np.polyfit(np.arange(len(y)), y, 1)[0]\n        delta = abs(pendiente) * serie.horizonte\n    else:\n        delta = 0.0\n    L = bajo - delta\n    return (max(L, 0.0) if (y > 0).all() else L), alto + delta\n\n\nREGLAS = [(\"sin cota\", cota_por_rango(np.inf)),\n          (\"rango observado\", cota_por_rango(0.0)),\n          (\"condicional a la tendencia\", cota_condicional)]\nCONDICIONAL = pd.DataFrame(\n    [{**resumen(por_serie(cota), etiqueta), **evaluar(cota)}\n     for etiqueta, cota in REGLAS]\n).set_index(\"regla\")\nCONDICIONAL[[\"pasos recortados\", \"sMAPE medio\", \"MASE medio\", \"MASE máximo\",\n             \"series que empeoran\", \"peor daño (puntos de sMAPE)\"]].round(\n    {\"pasos recortados\": 0, \"sMAPE medio\": 2, \"MASE medio\": 2, \"MASE máximo\": 1,\n     \"series que empeoran\": 0, \"peor daño (puntos de sMAPE)\": 2})\n```\n\n::: {.cell-output .cell-output-display execution_count=7}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>pasos recortados</th>\n      <th>sMAPE medio</th>\n      <th>MASE medio</th>\n      <th>MASE máximo</th>\n      <th>series que empeoran</th>\n      <th>peor daño (puntos de sMAPE)</th>\n    </tr>\n    <tr>\n      <th>regla</th>\n      <th></th>\n      <th></th>\n      <th></th>\n      <th></th>\n      <th></th>\n      <th></th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>sin cota</th>\n      <td>0</td>\n      <td>47.10</td>\n      <td>35.72</td>\n      <td>356.2</td>\n      <td>0</td>\n      <td>0.00</td>\n    </tr>\n    <tr>\n      <th>rango observado</th>\n      <td>298</td>\n      <td>31.40</td>\n      <td>15.72</td>\n      <td>116.2</td>\n      <td>5</td>\n      <td>5.65</td>\n    </tr>\n    <tr>\n      <th>condicional a la tendencia</th>\n      <td>249</td>\n      <td>31.28</td>\n      <td>15.76</td>\n      <td>116.6</td>\n      <td>3</td>\n      <td>0.73</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\nLa regla condicional deja de recortar\n49\npasos que eran tendencia legítima, y el peor daño baja de\n5\\,7 a\n0\\,7\npuntos de sMAPE, sin perder nada de la protección: las ganancias de cien puntos en las series donde\nHolt se desbarranca siguen ahí.\n\n**Esa es la cota que la aplicación de este proyecto tiene tomada como decisión**, y ahora está\nmedida: no es una regla de gusto sino una que sobre 35 series y\n649 pasos mejora el MASE medio un\n56 %\ny daña a lo sumo 0\\,7\npuntos a una sola serie.\n\n```{pyodide}\n#| caption: La cota de cordura sobre un pronóstico que se desbarranca — cambia `cual` y `margen`\n#| autorun: true\nimport numpy as np\nimport pandas as pd\nfrom statsmodels.tsa.holtwinters import Holt\n\ndatos = pd.read_csv(\"datos/cap01_series.csv\", parse_dates=[\"ds\"])\n\n# \"quiebre de nivel\" es donde Holt se va a valores negativos. Prueba\n# \"tendencia limpia\" para ver el otro lado: ahí la cota estorba.\ncual = \"quiebre de nivel\"\nmargen = 0.0                     # el c de la ecuación 25.1\n\n\ndef smape(real, pron):\n    real, pron = np.asarray(real, float), np.asarray(pron, float)\n    return 200 * np.mean(np.abs(real - pron) / (np.abs(real) + np.abs(pron)))\n\n\ndef mase(real, pron, entrenamiento, m):\n    y = np.asarray(entrenamiento, float)\n    d = np.mean(np.abs(y[m:] - y[:-m])) if len(y) > m > 1 else np.mean(np.abs(np.diff(y)))\n    return np.mean(np.abs(np.asarray(real, float) - np.asarray(pron, float))) / d\n\n\ng = datos[datos[\"etiqueta\"] == cual].sort_values(\"ds\")\ny = g[\"y\"].to_numpy(float)\nm = int(g[\"m\"].iloc[0])\nh = int((g[\"split\"] == \"prueba\").sum())\ny_tr, y_te = y[:-h], y[-h:]\n\npron = np.asarray(Holt(y_tr, initialization_method=\"estimated\").fit().forecast(h), float)\n\nbajo, alto = y_tr.min(), y_tr.max()\nrango = alto - bajo\nL = max(bajo - margen * rango, 0.0)      # la serie es positiva\nU = alto + margen * rango\nacotado = np.clip(pron, L, U)\n\nprint(f\"histórico: [{bajo:,.1f}, {alto:,.1f}]\")\nprint(f\"pronóstico sin cota: [{pron.min():,.1f}, {pron.max():,.1f}]\")\nprint(f\"pasos fuera de la cota: {int(((pron < L) | (pron > U)).sum())} de {h}\")\npd.DataFrame({\n    \"sMAPE\": [smape(y_te, pron), smape(y_te, acotado)],\n    \"MASE\": [mase(y_te, pron, y_tr, m), mase(y_te, acotado, y_tr, m)],\n}, index=[\"sin cota\", \"con cota\"]).round(2)\n```\n\n## La misma cota sobre el intervalo, que no es lo mismo {#sec-cota-intervalo}\n\nEl @sec-bootstrapping construyó intervalos por simulación y midió que cubren mucho menos de lo que\nprometen. Falta una pregunta de producción: **¿cuántos de esos intervalos incluyen valores\nimposibles?**\n\n::: {#tbl-cota-intervalo .cell tbl-cap='Intervalos del 95 % por bootstrap del naive estacional sobre las series del catálogo, con B = 500 trayectorias, y qué pasa al acotarlos.' execution_count=8}\n``` {.python .cell-code}\nrng = np.random.default_rng(42)\n\n\ndef paso_snaive(y, m):\n    return y[-m] if m > 1 else y[-1]\n\n\ndef residuos_snaive(y, m):\n    if m <= 1:\n        ajustado = np.concatenate([[np.nan], y[:-1]])\n    else:\n        ajustado = np.concatenate([np.full(m, np.nan), y[:-m]])\n    d = y - ajustado\n    return d[~np.isnan(d)]\n\n\nB = 500\nacumulado = {\"sin cota\": [0, 0.0], \"piso en cero\": [0, 0.0], \"rango observado\": [0, 0.0]}\nnegativos = pasos = series_con_negativo = 0\nfor s in SERIES:\n    y = s.entrenamiento.to_numpy(float)\n    real = s.prueba.to_numpy(float)\n    h, m = s.horizonte, max(s.periodo_estacional, 1)\n    r = residuos_snaive(y, m)\n    trayectorias = np.zeros((B, h))\n    for b in range(B):\n        historia = list(y)\n        for _ in range(h):\n            historia.append(paso_snaive(np.array(historia), m) + rng.choice(r))\n        trayectorias[b] = historia[-h:]\n    bajo = np.quantile(trayectorias, 0.025, axis=0)\n    alto = np.quantile(trayectorias, 0.975, axis=0)\n    positiva = (y > 0).all()\n    pasos += h\n    if positiva:\n        negativos += int((bajo < 0).sum())\n        series_con_negativo += int((bajo < 0).any())\n    variantes = {\n        \"sin cota\": (bajo, alto),\n        \"piso en cero\": (np.clip(bajo, 0, None) if positiva else bajo, alto),\n        \"rango observado\": (np.clip(bajo, max(y.min(), 0) if positiva else y.min(), None),\n                            np.clip(alto, None, y.max())),\n    }\n    for nombre, (lo, hi) in variantes.items():\n        acumulado[nombre][0] += int(((real >= lo) & (real <= hi)).sum())\n        acumulado[nombre][1] += float(np.sum(hi - lo))\n\nancho_base = acumulado[\"sin cota\"][1]\nINTERVALOS = pd.DataFrame([\n    {\"variante\": nombre, \"cobertura %\": 100 * cub / pasos, \"ancho relativo\": anc / ancho_base}\n    for nombre, (cub, anc) in acumulado.items()\n]).set_index(\"variante\")\nINTERVALOS.round(3)\n```\n\n::: {.cell-output .cell-output-display execution_count=8}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>cobertura %</th>\n      <th>ancho relativo</th>\n    </tr>\n    <tr>\n      <th>variante</th>\n      <th></th>\n      <th></th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>sin cota</th>\n      <td>81.510</td>\n      <td>1.000</td>\n    </tr>\n    <tr>\n      <th>piso en cero</th>\n      <td>81.510</td>\n      <td>0.772</td>\n    </tr>\n    <tr>\n      <th>rango observado</th>\n      <td>72.111</td>\n      <td>0.570</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\nEl extremo inferior es negativo en 16\\,6 % de los\n649 pasos, en 12 de las 35 series, siempre en\nseries cuyo histórico es estrictamente positivo. Un intervalo que dice \"entre −400 y 1.200 unidades\"\nno es conservador: es un error visible.\n\nY las dos maneras de arreglarlo no son equivalentes.\n\n**Poner un piso en cero no cuesta nada.** La cobertura queda en\n81\\,5 %, idéntica a la de partida, y el\nintervalo se angosta un\n23 %. La región que se\nrecorta no contenía ningún valor real, porque ningún valor real es negativo.\n\n**Acotar el intervalo al rango observado cuesta caro.** La cobertura baja a\n72\\,1 %, o sea\n9\\,4\npuntos menos, porque los valores reales sí salen del rango histórico y el intervalo estaba ahí\njustamente para admitirlos.\n\n::: {.callout-tip}\n## La cota del punto y la cota del intervalo son distintas\n\nSobre el pronóstico puntual, la cota apretada gana: la @sec-cota-cordura midió que recortar al rango\nobservado —con la corrección por tendencia— mejora todo.\n\nSobre el intervalo, la cota apretada pierde: recortar al rango observado le saca\n9\npuntos de cobertura a un intervalo que ya cubría menos de lo que prometía.\n\nLa regla que sale de las dos mediciones es asimétrica, y no es obvia: **al punto, cota estadística;\nal intervalo, solo cota física.** El punto es una apuesta y conviene que sea prudente; el intervalo\nes una declaración de incertidumbre y angostarlo es mentir.\n:::\n\n## Los casos que M4 no contiene {#sec-casos-limite}\n\nEl @sec-los-datos mostró que M4 filtró por longitud mínima: no hay series de ocho puntos, ni de\npuros ceros, ni con valores negativos. Una aplicación las recibe el primer día. Esta tabla ejecuta\nlas herramientas del libro sobre esos casos y anota lo que devuelven.\n\n::: {#tbl-limites .cell tbl-cap='Qué hace cada herramienta con una entrada que M4 no contiene. La columna final distingue el error que se ve del que no.' execution_count=9}\n``` {.python .cell-code}\nfrom sklearn.linear_model import Ridge\nfrom statsmodels.tsa.arima.model import ARIMA\nfrom statsmodels.tsa.holtwinters import ExponentialSmoothing\nfrom statsmodels.tsa.seasonal import STL\n\nCORTA = np.array([10.0, 11.0, 12.0])\nCEROS = np.array([0.0, 0, 5, 0, 0, 7, 0, 0, 3, 0, 0, 9])\nCONSTANTE = np.repeat(4.0, 30)\nCON_NAN = np.array([1.0, 2, np.nan, 4, 5, 6, 7, 8, 9, 10, 11, 12])\n\n\ndef intentar(f):\n    \"\"\"Ejecuta f y clasifica el resultado en excepción, silencioso o correcto.\"\"\"\n    try:\n        r = np.atleast_1d(np.asarray(f(), float))\n    except Exception as e:\n        return f\"{type(e).__name__}\", \"falla ruidosa\"\n    if np.isnan(r).any():\n        return \"devuelve nan\", \"falla silenciosa\"\n    if np.isinf(r).any():\n        return \"devuelve inf\", \"falla silenciosa\"\n    return f\"devuelve {np.round(r[0], 2)}\", \"sin aviso\"\n\n\nCASOS = [\n    (\"serie de 3 puntos, m = 12\", \"STL\",\n     lambda: STL(pd.Series(CORTA), period=12).fit().trend),\n    (\"serie de 3 puntos, m = 12\", \"ETS estacional\",\n     lambda: ExponentialSmoothing(CORTA, seasonal=\"add\", seasonal_periods=12,\n                                  initialization_method=\"estimated\").fit().forecast(6)),\n    (\"serie de 3 puntos, m = 12\", \"naive estacional\",\n     lambda: np.array([CORTA[-12 + (i % 12)] for i in range(6)])),\n    (\"serie de 3 puntos, m = 12\", \"MASE\",\n     lambda: [mase([4.0, 4], [5.0, 5], CORTA, 12)]),\n    (\"serie con ceros\", \"logaritmo\", lambda: np.log(CEROS)),\n    (\"serie con ceros\", \"MAPE\",\n     lambda: [np.mean(np.abs((np.array([1.0, 5]) - np.array([0.0, 5])) / np.array([0.0, 5])))]),\n    (\"serie con ceros\", \"sMAPE\", lambda: [smape([0.0, 5], [0.0, 5])]),\n    (\"serie constante\", \"ARIMA(1,1,1)\",\n     lambda: ARIMA(CONSTANTE, order=(1, 1, 1)).fit().forecast(6)),\n    (\"serie constante\", \"MASE\",\n     lambda: [mase([4.0, 4], [5.0, 5], CONSTANTE, 1)]),\n    (\"serie con un faltante\", \"Ridge\",\n     lambda: Ridge().fit(CON_NAN[:-1].reshape(-1, 1), CON_NAN[1:]).predict([[12.0]])),\n]\nfilas = []\nfor entrada, herramienta, f in CASOS:\n    resultado, clase = intentar(f)\n    filas.append({\"entrada\": entrada, \"herramienta\": herramienta,\n                  \"resultado\": resultado, \"tipo\": clase})\nLIMITES = pd.DataFrame(filas).set_index([\"entrada\", \"herramienta\"])\nLIMITES\n```\n\n::: {.cell-output .cell-output-display execution_count=9}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th></th>\n      <th>resultado</th>\n      <th>tipo</th>\n    </tr>\n    <tr>\n      <th>entrada</th>\n      <th>herramienta</th>\n      <th></th>\n      <th></th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th rowspan=\"4\" valign=\"top\">serie de 3 puntos, m = 12</th>\n      <th>STL</th>\n      <td>devuelve 9.26</td>\n      <td>sin aviso</td>\n    </tr>\n    <tr>\n      <th>ETS estacional</th>\n      <td>ValueError</td>\n      <td>falla ruidosa</td>\n    </tr>\n    <tr>\n      <th>naive estacional</th>\n      <td>IndexError</td>\n      <td>falla ruidosa</td>\n    </tr>\n    <tr>\n      <th>MASE</th>\n      <td>devuelve 1.0</td>\n      <td>sin aviso</td>\n    </tr>\n    <tr>\n      <th rowspan=\"3\" valign=\"top\">serie con ceros</th>\n      <th>logaritmo</th>\n      <td>devuelve inf</td>\n      <td>falla silenciosa</td>\n    </tr>\n    <tr>\n      <th>MAPE</th>\n      <td>devuelve inf</td>\n      <td>falla silenciosa</td>\n    </tr>\n    <tr>\n      <th>sMAPE</th>\n      <td>devuelve nan</td>\n      <td>falla silenciosa</td>\n    </tr>\n    <tr>\n      <th rowspan=\"2\" valign=\"top\">serie constante</th>\n      <th>ARIMA(1,1,1)</th>\n      <td>devuelve 4.0</td>\n      <td>sin aviso</td>\n    </tr>\n    <tr>\n      <th>MASE</th>\n      <td>devuelve inf</td>\n      <td>falla silenciosa</td>\n    </tr>\n    <tr>\n      <th>serie con un faltante</th>\n      <th>Ridge</th>\n      <td>ValueError</td>\n      <td>falla ruidosa</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\nTres cosas de esa tabla.\n\n**Las fallas ruidosas son las baratas.** El naive estacional con $m = 12$ y tres puntos levanta un\n`IndexError`, `Ridge` con un faltante levanta un `ValueError`. Molestan en el momento y no llegan\nal usuario.\n\n**Las silenciosas son el problema.** 4\nde los 10 casos devuelven `nan` o `inf` sin avisar: el logaritmo de un\ncero, el MAPE con un cero en la prueba, el sMAPE cuando el real y el pronóstico son ambos cero, el\nMASE cuando la serie es constante y el denominador se anula. Un `nan` que atraviesa un promedio se\nconvierte en un `nan` en la interfaz, o —peor— en una fila que alguien filtró y nadie contó.\n\n**Y hay una tercera categoría, la más peligrosa: la respuesta sin sentido y sin aviso.** Son\n3 de los diez. STL con tres puntos y\nperíodo 12 **devuelve una tendencia**. ARIMA(1,1,1) sobre una serie constante **devuelve un\npronóstico**. Y el MASE con $m = 12$ sobre tres puntos **devuelve un número**, pero no el que se\npidió: la función de este libro cae al naive no estacional cuando $n \\le m$, que es una decisión\nrazonable y queda invisible en la salida. Nada en ninguno de los tres indica que el pedido no tenía\nsentido.\n\n::: {.callout-important}\n## La validación de entrada va antes del modelo\n\nDe la tabla sale una lista corta de comprobaciones que ninguna biblioteca hace por ti, y que\nconviene hacer **antes** de elegir método:\n\n1. $n \\ge 2m + 1$ para cualquier método estacional, y $n \\ge 3m$ para estimar una estacionalidad\n   con algo de estabilidad.\n2. Serie no constante: si la varianza es cero, el pronóstico es la constante y el MASE no existe.\n3. Sin faltantes, o con una política explícita de relleno.\n4. Registrar si la serie tiene ceros o negativos, porque decide qué métricas y qué\n   transformaciones se pueden usar.\n5. Comparar $h$ con $n$: pronosticar 48 pasos desde 20 observaciones es una operación legal que no\n   significa nada.\n\nEl @sec-los-datos las presentó como higiene de datos. Acá son la diferencia entre un error de\npantalla y un número inventado.\n:::\n\n## Qué hay que guardar {#sec-servir}\n\nEl @sec-prediccion comparó las estrategias multipaso por precisión y por tiempo de ajuste, y dejó\npendiente el costo de almacenamiento. Con $S$ series, $h$ pasos y $b$ bytes por modelo serializado,\n\n$$\n\\text{recursiva} = S \\cdot b,\n\\qquad\n\\text{directa} = S \\cdot h \\cdot b,\n$$ {#eq-almacenamiento}\n\nque es una diferencia de un factor $h$: 48 para las series horarias de M4. El tamaño $b$, en cambio,\nno depende de la estrategia sino del modelo, y esa es la parte que la @eq-almacenamiento no dice.\n\n::: {#tbl-almacenamiento .cell tbl-cap='Tamaño serializado con `pickle` de los modelos ajustados sobre la serie horaria H272 (n = 960, h = 48, 48 rezagos), y la extrapolación a las 99.935 series de M4.' execution_count=10}\n``` {.python .cell-code}\nfrom sklearn.compose import TransformedTargetRegressor\nfrom sklearn.ensemble import HistGradientBoostingRegressor\nfrom sklearn.neural_network import MLPRegressor\nfrom sklearn.pipeline import make_pipeline\nfrom sklearn.preprocessing import StandardScaler\n\ns = cargar(\"H272\")\ny_h272 = s.entrenamiento.to_numpy(float)\nP_REZAGOS, H_H272 = 48, s.horizonte\n\n\ndef tabla_directa(y, p, k):\n    \"\"\"Matriz de rezagos con el objetivo a k pasos (la @eq-directa).\"\"\"\n    X = np.array([y[i - p:i] for i in range(p, len(y) - k + 1)])\n    objetivo = np.array([y[i + k - 1] for i in range(p, len(y) - k + 1)])\n    return X, objetivo\n\n\ndef red():\n    return TransformedTargetRegressor(\n        make_pipeline(StandardScaler(),\n                      MLPRegressor(hidden_layer_sizes=(100,), max_iter=300, random_state=0)),\n        transformer=StandardScaler())\n\n\nMODELOS = {\"Ridge\": Ridge,\n           \"boosting por histogramas\": lambda: HistGradientBoostingRegressor(max_iter=100),\n           \"perceptrón (100 neuronas)\": red}\nfilas = []\nfor nombre, constructor in MODELOS.items():\n    X, objetivo = tabla_directa(y_h272, P_REZAGOS, 1)\n    bytes_uno = len(pickle.dumps(constructor().fit(X, objetivo)))\n    bytes_todos = 0\n    for k in range(1, H_H272 + 1):\n        X, objetivo = tabla_directa(y_h272, P_REZAGOS, k)\n        bytes_todos += len(pickle.dumps(constructor().fit(X, objetivo)))\n    filas.append({\"modelo\": nombre,\n                  \"recursiva (kB)\": bytes_uno / 1e3,\n                  \"directa (kB)\": bytes_todos / 1e3,\n                  \"recursiva × 99.935 (GB)\": bytes_uno * 99_935 / 1e9,\n                  \"directa × 99.935 (GB)\": bytes_todos * 99_935 / 1e9})\nALMACEN = pd.DataFrame(filas).set_index(\"modelo\")\nALMACEN.round(2)\n```\n\n::: {.cell-output .cell-output-display execution_count=10}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>recursiva (kB)</th>\n      <th>directa (kB)</th>\n      <th>recursiva × 99.935 (GB)</th>\n      <th>directa × 99.935 (GB)</th>\n    </tr>\n    <tr>\n      <th>modelo</th>\n      <th></th>\n      <th></th>\n      <th></th>\n      <th></th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>Ridge</th>\n      <td>0.83</td>\n      <td>39.70</td>\n      <td>0.08</td>\n      <td>3.97</td>\n    </tr>\n    <tr>\n      <th>boosting por histogramas</th>\n      <td>418.12</td>\n      <td>20060.52</td>\n      <td>41.78</td>\n      <td>2004.75</td>\n    </tr>\n    <tr>\n      <th>perceptrón (100 neuronas)</th>\n      <td>171.00</td>\n      <td>8229.65</td>\n      <td>17.09</td>\n      <td>822.43</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\nEl factor entre columnas es 48, como manda la @eq-almacenamiento. Lo que la ecuación no anticipa es\nel factor entre filas: el boosting ocupa\n506\nveces más que Ridge para el mismo problema, porque guarda cien árboles y Ridge guarda 48\ncoeficientes.\n\nPuestos juntos, los dos factores dan una conclusión que cambia el diseño de un sistema:\n\n- Ridge con estrategia **directa**, para las 99.935 series:\n  4\\,0 GB.\n- Boosting con estrategia **recursiva**:\n  42 GB.\n- Boosting con estrategia directa:\n  2\\,0\n  **terabytes**.\n\nO sea: **elegir el modelo pesa más que elegir la estrategia.** La combinación cara no es la directa,\nes la directa con un modelo grande, y esa combinación es exactamente la que el @sec-prediccion\nmostró que tampoco gana en precisión.\n\n## Cuánto tarda {#sec-latencia}\n\nLa @sec-costo midió el pipeline de la tesis en 16,6 horas y encontró que el 83 % se lo lleva\n`sample_entropy`, con 19,7 segundos en una serie de 4.000 puntos. Para una aplicación la pregunta no\nes el total sino la latencia por serie: cuánto espera alguien que acaba de subir un archivo.\n\n::: {#tbl-latencia .cell tbl-cap='Tiempo de cálculo por serie de tres grupos de características, sobre series del catálogo de longitud creciente. Las dos últimas columnas son la misma cuenta con dos implementaciones.' execution_count=11}\n``` {.python .cell-code}\nfrom statsmodels.tsa.stattools import acf, adfuller\n\n\ndef caracteristicas_baratas(y):\n    \"\"\"Siete descriptores de costo O(n): todos son una pasada sobre la serie.\"\"\"\n    d = np.diff(y)\n    mediana = np.median(y)\n    mad = np.median(np.abs(y - mediana))\n    return {\n        \"n\": len(y),\n        \"cv\": y.std() / abs(y.mean()),\n        \"acf1\": acf(y, nlags=1)[1],\n        \"razon_varianzas\": d.var() / y.var(),\n        \"atipicos\": float(np.mean(np.abs(y - mediana) > 3 * mad + 1e-12)),\n        \"giros\": float(np.mean(np.diff(np.sign(d)) != 0)),\n        \"pendiente\": np.polyfit(np.arange(len(y)), y, 1)[0] / y.std(),\n    }\n\n\ndef caracteristicas_medias(y, m):\n    \"\"\"Descomposición y prueba de raíz unitaria: O(n log n) con constantes grandes.\"\"\"\n    if m > 1 and len(y) > 2 * m:\n        STL(pd.Series(y), period=m).fit()\n    return adfuller(y, autolag=\"AIC\")[1]\n\n\ndef entropia_con_bucles(x, m=2, r=0.2):\n    \"\"\"La versión de la tesis: dos bucles de Python, O(n²).\"\"\"\n    x = (x - x.mean()) / x.std()\n    n = len(x)\n\n    def coincidencias(largo):\n        plantillas = [x[i:i + largo] for i in range(n - largo + 1)]\n        total = 0\n        for i in range(len(plantillas)):\n            for j in range(i + 1, len(plantillas)):\n                if max(abs(plantillas[i] - plantillas[j])) <= r:\n                    total += 1\n        return total\n\n    a, b = coincidencias(m + 1), coincidencias(m)\n    return -np.log(a / b) if a > 0 and b > 0 else np.nan\n\n\ndef entropia_vectorizada(x, m=2, r=0.2):\n    \"\"\"La misma cuenta con el bucle interno en numpy. Devuelve el mismo número.\"\"\"\n    x = (x - x.mean()) / x.std()\n    n = len(x)\n\n    def coincidencias(largo):\n        plantillas = np.array([x[i:i + largo] for i in range(n - largo + 1)])\n        total = 0\n        for i in range(len(plantillas)):\n            distancia = np.max(np.abs(plantillas[i + 1:] - plantillas[i]), axis=1)\n            total += int((distancia <= r).sum())\n        return total\n\n    a, b = coincidencias(m + 1), coincidencias(m)\n    return -np.log(a / b) if a > 0 and b > 0 else np.nan\n\n\ndef cronometrar(f):\n    inicio = time.perf_counter()\n    valor = f()\n    return 1000 * (time.perf_counter() - inicio), valor\n\n\nfilas = []\nfor sid in [\"M39292\", \"M32692\", \"H272\", \"M17144\"]:\n    s = cargar(sid)\n    y = s.entrenamiento.to_numpy(float)\n    m = max(s.periodo_estacional, 1)\n    recortada = y[:4000]                      # el tope que usó la tesis\n    t_baratas, _ = cronometrar(lambda: caracteristicas_baratas(y))\n    t_medias, _ = cronometrar(lambda: caracteristicas_medias(y, m))\n    t_bucles, valor_bucles = cronometrar(lambda: entropia_con_bucles(recortada))\n    t_vector, valor_vector = cronometrar(lambda: entropia_vectorizada(recortada))\n    filas.append({\n        \"serie\": sid, \"n\": len(y),\n        \"siete baratas (ms)\": t_baratas,\n        \"STL y raíz unitaria (ms)\": t_medias,\n        \"entropía con bucles (ms)\": t_bucles,\n        \"entropía vectorizada (ms)\": t_vector,\n        \"factor\": t_bucles / t_vector,\n        \"diferencia entre las dos\": abs(valor_bucles - valor_vector),\n    })\nLATENCIA = pd.DataFrame(filas).set_index(\"serie\")\nLATENCIA.round(3)\n```\n\n::: {.cell-output .cell-output-display execution_count=11}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>n</th>\n      <th>siete baratas (ms)</th>\n      <th>STL y raíz unitaria (ms)</th>\n      <th>entropía con bucles (ms)</th>\n      <th>entropía vectorizada (ms)</th>\n      <th>factor</th>\n      <th>diferencia entre las dos</th>\n    </tr>\n    <tr>\n      <th>serie</th>\n      <th></th>\n      <th></th>\n      <th></th>\n      <th></th>\n      <th></th>\n      <th></th>\n      <th></th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>M39292</th>\n      <td>125</td>\n      <td>0.306</td>\n      <td>2.117</td>\n      <td>8.104</td>\n      <td>0.988</td>\n      <td>8.198</td>\n      <td>0.0</td>\n    </tr>\n    <tr>\n      <th>M32692</th>\n      <td>318</td>\n      <td>0.212</td>\n      <td>3.175</td>\n      <td>53.467</td>\n      <td>2.985</td>\n      <td>17.912</td>\n      <td>0.0</td>\n    </tr>\n    <tr>\n      <th>H272</th>\n      <td>960</td>\n      <td>0.230</td>\n      <td>11.446</td>\n      <td>488.845</td>\n      <td>15.992</td>\n      <td>30.568</td>\n      <td>0.0</td>\n    </tr>\n    <tr>\n      <th>M17144</th>\n      <td>2794</td>\n      <td>0.344</td>\n      <td>30.080</td>\n      <td>4138.858</td>\n      <td>106.232</td>\n      <td>38.961</td>\n      <td>0.0</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\nLas dos implementaciones devuelven el mismo número —la última columna es la diferencia entre las\ndos, y es cero en las cuatro series— y difieren en un factor que crece\ncon la longitud: 8 veces en la serie más corta y\n39 en la más larga.\n\nEso **contesta el pendiente que dejó la @sec-costo**, y lo contesta distinto de lo que ese capítulo\nanticipaba. La conclusión de allá fue que el índice, para calcularse en línea, había que vectorizarlo\no precomputarlo. Medido acá: vectorizarlo alcanza. Los\n4\\,1 segundos de la serie de\n2\\.794 puntos se convierten en\n106 milisegundos sin cambiar el\nresultado, y las 16,6 horas del pipeline completo caen al mismo ritmo.\n\nContra un presupuesto de 100 ms por serie —el límite de lo que se percibe como instantáneo— la\ntabla se lee así:\n\n- Las siete características baratas entran siempre con margen enorme: el máximo medido es\n  0\\,34 ms.\n- STL y la prueba de raíz unitaria entran en las series cortas y se van del presupuesto en las\n  largas: 30 ms en la serie de\n  2\\.794 puntos.\n- La entropía muestral con bucles se va del presupuesto alrededor de los quinientos puntos\n  (489 ms con\n  960); vectorizada aguanta hasta unos pocos miles\n  (106 ms con\n  2\\.794).\n\n::: {#tbl-latencia-larga .cell tbl-cap='La serie más larga del catálogo, sin el tope de 4.000 puntos, con la implementación vectorizada.' execution_count=12}\n``` {.python .cell-code}\ns = cargar(\"D4099\")\ny_larga = s.entrenamiento.to_numpy(float)\nt_completa, _ = cronometrar(lambda: entropia_vectorizada(y_larga))\nt_recorte, _ = cronometrar(lambda: entropia_vectorizada(y_larga[:4000]))\nLARGA = pd.DataFrame([\n    {\"entrada\": f\"completa (n = {len(y_larga)})\", \"milisegundos\": t_completa},\n    {\"entrada\": \"recortada a 4.000\", \"milisegundos\": t_recorte},\n]).set_index(\"entrada\")\nLARGA.round(0)\n```\n\n::: {.cell-output .cell-output-display execution_count=12}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>milisegundos</th>\n    </tr>\n    <tr>\n      <th>entrada</th>\n      <th></th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>completa (n = 9919)</th>\n      <td>1230.0</td>\n    </tr>\n    <tr>\n      <th>recortada a 4.000</th>\n      <td>211.0</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\nEn la serie más larga del catálogo, sin recorte, la versión vectorizada tarda\n1\\,2 segundos:\nsigue afuera del presupuesto interactivo. El costo crece con $n^2$ y ninguna vectorización cambia\neso.\n\nDe las dos mediciones sale una regla con dos tramos, no una: **vectorizar resuelve el caso típico y\nrecortar resuelve la cola.** Un tope de 4.000 puntos deja el cálculo en\n211 ms para cualquier serie, y es\nexactamente lo que la tesis hizo por razones de costo total.\n\nY hay una salida mejor todavía, que la @sec-que-importa ya había medido sin buscarla: el clasificador\nque aprende a elegir método **no pierde nada** al quedarse sin `sample_entropy`. Para decidir no hace\nfalta; para diagnosticar se puede calcular después de responder.\n\n**La regla de diseño es medir la latencia por serie contra un presupuesto explícito, no el costo\ntotal del lote.** Son dos números distintos y llevan a decisiones distintas: el costo total se\nresuelve comprando máquinas, la latencia por serie no.\n\n## Promediar el azar {#sec-semillas-produccion}\n\nEl @sec-aprendizaje-profundo reprodujo el hallazgo central de la tesis: dos entrenamientos de la\nmisma red sobre la misma serie, cambiando solo la semilla, dan errores distintos. En un experimento\neso es una barra de error. En producción es un usuario que refresca la página y ve otro número.\n\nLa respuesta es un ensamble de semillas: entrenar $J$ veces y combinar. @bouthillier2021 miden el\nefecto de esa varianza sobre comparaciones publicadas y muestran que alcanza para invertir el orden\nentre métodos, que es exactamente lo que la tesis encontró con las redes.\n\nCon $\\hat y^{(j)}_{t+k}$ el pronóstico de la semilla $j$,\n\n$$\n\\hat y^{\\text{ens}}_{t+k} = \\operatorname{mediana}_{j=1,\\dots,J} \\hat y^{(j)}_{t+k},\n$$ {#eq-ensamble-semillas}\n\ny la mediana en vez del promedio porque el @sec-ensambles midió que la divergencia entre las dos\nseñala una cola, y acá la cola es justamente el entrenamiento que salió mal.\n\n::: {#tbl-semillas-produccion .cell tbl-cap='Perceptrón de 32 neuronas, estrategia recursiva, sobre las series del catálogo con largo suficiente. Cinco semillas, y las dos combinaciones.' execution_count=13}\n``` {.python .cell-code}\ndef ventanas(y, p):\n    X = np.array([y[i - p:i] for i in range(p, len(y))])\n    return X, y[p:]\n\n\ndef recursivo(modelo, y, p, h):\n    historia, salida = list(y), []\n    for _ in range(h):\n        salida.append(float(modelo.predict(np.array(historia[-p:]).reshape(1, -1))[0]))\n        historia.append(salida[-1])\n    return np.array(salida)\n\n\ndef perceptron(semilla):\n    return TransformedTargetRegressor(\n        make_pipeline(StandardScaler(),\n                      MLPRegressor(hidden_layer_sizes=(32,), max_iter=500,\n                                   random_state=semilla)),\n        transformer=StandardScaler())\n\n\nSEMILLAS = range(5)\nfilas = []\ntiempo_una = tiempo_todas = 0.0\nfor s in SERIES:\n    y = s.entrenamiento.to_numpy(float)\n    h, m = s.horizonte, max(s.periodo_estacional, 1)\n    p = max(2 * m, 8)\n    if len(y) < p + 12:\n        continue\n    real = s.prueba.to_numpy(float)\n    X, objetivo = ventanas(y, p)\n    pronosticos = []\n    inicio = time.perf_counter()\n    for semilla in SEMILLAS:\n        pronosticos.append(recursivo(perceptron(semilla).fit(X, objetivo), y, p, h))\n        if semilla == 0:\n            tiempo_una += time.perf_counter() - inicio\n    tiempo_todas += time.perf_counter() - inicio\n    P = np.array(pronosticos)\n    errores = [smape(real, P[j]) for j in range(len(SEMILLAS))]\n    filas.append({\"serie\": s.id,\n                  **{f\"semilla {j}\": errores[j] for j in SEMILLAS},\n                  \"mediana\": smape(real, np.median(P, axis=0)),\n                  \"promedio\": smape(real, P.mean(axis=0)),\n                  \"mejor semilla\": min(errores),\n                  \"peor semilla\": max(errores)})\nSEM = pd.DataFrame(filas).set_index(\"serie\")\nSEM.mean().to_frame(\"sMAPE medio\").round(2).T\n```\n\n::: {.cell-output .cell-output-display execution_count=13}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>semilla 0</th>\n      <th>semilla 1</th>\n      <th>semilla 2</th>\n      <th>semilla 3</th>\n      <th>semilla 4</th>\n      <th>mediana</th>\n      <th>promedio</th>\n      <th>mejor semilla</th>\n      <th>peor semilla</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>sMAPE medio</th>\n      <td>24.27</td>\n      <td>20.55</td>\n      <td>24.17</td>\n      <td>23.77</td>\n      <td>23.12</td>\n      <td>21.37</td>\n      <td>21.14</td>\n      <td>16.68</td>\n      <td>30.8</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\nNinguna semilla es la buena. La distancia entre la mejor y la peor es de\n14\\,1 puntos de sMAPE en\npromedio, y en la serie mediana la peor semilla erra un\n55 %\nmás que la mejor. Sobre 32 series:\n\n- La mediana de las cinco le gana a la semilla 0 —la que sale de fijar `random_state=0` y no\n  pensarlo más— en 22 de\n  32 series.\n- La mediana no alcanza a la mejor semilla\n  (21\\,37 contra\n  16\\,68), y no puede: la mejor semilla es un oráculo que\n  solo se conoce mirando la prueba.\n- Lo que la mediana compra es no caer en la peor\n  (30\\,80), que es el riesgo real de tirar una sola vez.\n- Cuesta 4\\,6 veces el tiempo de una sola.\n\n**Tres a cinco semillas con la mediana es la decisión que la aplicación de este proyecto tiene\ntomada**, y estos son los números que la sostienen: no mejora el promedio de manera espectacular,\nelimina el peor resultado, y el costo es lineal y paralelizable.\n\n## Cada cuánto reajustar {#sec-reajustar}\n\nEl @sec-particiones midió si reajustar el modelo con los datos nuevos vale la pena y encontró que\nla ganancia es chica. Producción hace una pregunta más precisa: **cuánto se degrada un ajuste\nmientras envejece.**\n\nEl experimento: cortar cada serie larga $K = 6$ horizontes antes del final, ajustar Ridge una sola\nvez ahí, y pronosticar los seis bloques siguientes sin volver a ajustar —usando siempre los datos\nreales como entrada, solo con los coeficientes viejos— contra reajustar en cada origen.\n\n::: {#tbl-antiguedad .cell tbl-cap='Penalización por usar un ajuste viejo, por antigüedad medida en horizontes. Comparación pareada sobre los mismos orígenes.' execution_count=14}\n``` {.python .cell-code}\nK = 6\nregistro = []\nfor s in SERIES:\n    y = s.entrenamiento.to_numpy(float)\n    h, m = s.horizonte, max(s.periodo_estacional, 1)\n    p = max(2 * m, 8)\n    n0 = len(y) - K * h\n    if n0 < 4 * p:\n        continue\n    X, objetivo = ventanas(y[:n0], p)\n    congelado = Ridge().fit(X, objetivo)\n    for k in range(K):\n        inicio = n0 + k * h\n        real = y[inicio:inicio + h]\n        X_k, objetivo_k = ventanas(y[:inicio], p)\n        registro.append({\n            \"serie\": s.id, \"antigüedad\": k,\n            \"congelado\": smape(real, recursivo(congelado, y[:inicio], p, h)),\n            \"reajustado\": smape(real, recursivo(Ridge().fit(X_k, objetivo_k), y[:inicio], p, h)),\n        })\nREG = pd.DataFrame(registro)\nANTIG = REG.groupby(\"antigüedad\").apply(\n    lambda x: pd.Series({\n        \"congelado\": x[\"congelado\"].mean(),\n        \"reajustado\": x[\"reajustado\"].mean(),\n        \"penalización mediana %\": 100 * np.nanmedian(\n            (x[\"congelado\"] - x[\"reajustado\"]) / x[\"reajustado\"]),\n        \"el congelado pierde %\": 100 * (x[\"congelado\"] > x[\"reajustado\"]).mean(),\n    }), include_groups=False)\nANTIG.round(2)\n```\n\n::: {.cell-output .cell-output-display execution_count=14}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>congelado</th>\n      <th>reajustado</th>\n      <th>penalización mediana %</th>\n      <th>el congelado pierde %</th>\n    </tr>\n    <tr>\n      <th>antigüedad</th>\n      <th></th>\n      <th></th>\n      <th></th>\n      <th></th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>7.77</td>\n      <td>7.77</td>\n      <td>0.00</td>\n      <td>0.00</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>5.41</td>\n      <td>9.80</td>\n      <td>3.12</td>\n      <td>76.19</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>11.17</td>\n      <td>10.79</td>\n      <td>7.68</td>\n      <td>61.90</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>23.81</td>\n      <td>23.40</td>\n      <td>7.09</td>\n      <td>66.67</td>\n    </tr>\n    <tr>\n      <th>4</th>\n      <td>20.65</td>\n      <td>17.58</td>\n      <td>7.80</td>\n      <td>66.67</td>\n    </tr>\n    <tr>\n      <th>5</th>\n      <td>23.42</td>\n      <td>10.07</td>\n      <td>19.33</td>\n      <td>90.48</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\nCon 21 series y 126 orígenes, la\nantigüedad 0 es idéntica por construcción y de ahí en adelante el ajuste viejo pierde cada vez más\nseguido: 76 % de los orígenes a un horizonte\nde distancia, 90 % a\n5 horizontes, con una penalización mediana que llega al\n19 %.\n\nLa serie es corta y el ruido es visible —hay una antigüedad donde el congelado gana en promedio—,\nasí que el número que vale es la frecuencia con que pierde, que sí crece de manera consistente.\n\nY la conclusión práctica no sale del tamaño de la penalización sino de compararla con el costo. Con\nRidge, reajustar todas las series del catálogo cuesta milisegundos; con el boosting de la\n@tbl-almacenamiento cuesta minutos y\n42 GB de\nreescritura. **La respuesta a \"cada cuánto reajustar\" es una función del costo de ajustar, no de la\ndegradación**, y por eso un modelo lineal barato puede reajustarse en cada origen mientras uno\ngrande se reajusta por lote.\n\n## El entorno para lo que el navegador no da {#sec-entorno}\n\nEl @sec-aprendizaje-profundo explicó por qué este libro no entrena una LSTM: Pyodide no trae\nPyTorch ni TensorFlow, y el libro no publica números que no puede ejecutar. Si quieres reproducir esa\nparte de la tesis, hace falta salir del navegador.\n\nLo mínimo, con la misma versión de Python que usa el libro:\n\n```bash\npython3 -m venv ~/.venvs/profundo\n~/.venvs/profundo/bin/pip install torch numpy pandas scikit-learn\n```\n\nTres cosas que la medición de este capítulo vuelve a poner sobre la mesa antes de entrenar nada.\n\n**Fijar las semillas no alcanza.** `torch.manual_seed` hace reproducible una corrida, no la\nconvierte en la corrida correcta. La @eq-ensamble-semillas sigue siendo necesaria, y con redes\nrecurrentes la dispersión que midió la tesis es mayor que la del perceptrón de la\n@tbl-semillas-produccion.\n\n**El tamaño serializado es otro.** La @tbl-almacenamiento muestra que un perceptrón de 100 neuronas\nya pesa 171 kB por serie.\nUna LSTM por serie, con estrategia directa, es un sistema de almacenamiento antes que un sistema de\npronóstico —y es justamente el argumento de la @sec-modelo-global a favor de un modelo global.\n\n**El aparato de defensa no cambia.** La cota de la @eq-cota-condicional, la validación de entrada\nde la @sec-casos-limite y el presupuesto de latencia de la @sec-latencia son independientes del modelo.\nUna red no necesita menos defensas: necesita las mismas, y con más urgencia, porque falla de maneras\nque no se anticipan leyendo sus parámetros.\n\n## La lista de verificación {#sec-lista-produccion}\n\nLas listas de comprobación para sistemas de aprendizaje automático existen y son más largas que esta\n—@breck2017 proponen veintiocho pruebas agrupadas en cuatro áreas—. Lo que sigue no las reemplaza:\nes lo que este capítulo midió, con el número al lado.\n\n| pregunta | respuesta medida acá |\n|---|---|\n| ¿alcanza el error medio para decidir? | no: el 22 % del hueco está en el 1 % de las series |\n| ¿conviene acotar el pronóstico puntual? | sí: el MASE medio baja un 56 % y el peor caso a un tercio |\n| ¿la cota va al rango observado? | sí, salvo que la serie tenga tendencia; ahí hay que dar espacio |\n| ¿sirve un piso en cero? | como cota física del intervalo sí; como piso del punto no |\n| ¿conviene acotar el intervalo al rango? | no: cuesta 9 puntos de cobertura |\n| ¿qué falla con entradas raras? | 4 de 10 casos devuelven `nan` o `inf` sin avisar, y 3 devuelven un número sin sentido |\n| ¿qué pesa más, la estrategia o el modelo? | el modelo: entre Ridge y boosting hay un factor de 500 |\n| ¿qué características entran en un presupuesto de 100 ms? | las de una pasada siempre; `sample_entropy` solo vectorizada y con tope |\n| ¿cuántas semillas? | tres a cinco, combinadas con la mediana |\n| ¿cada cuánto reajustar? | tan seguido como el costo de ajustar lo permita |\n\n: Lo que este capítulo mide, en una tabla. {#tbl-lista-produccion}\n\n## Lo que este libro deja hecho, y lo que no {#sec-cierre-libro}\n\nVeinticinco capítulos, todos ejecutables, sobre las mismas 100.000 series. Lo que queda escrito, más\nallá de los métodos, son unas cuantas cosas que la práctica corriente repite y que acá se midieron y\nsalieron distinto.\n\n- El promedio de dos pronósticos **no** le gana a elegir uno solo, en este catálogo\n  (@sec-ensambles).\n- La validación cruzada temporal **no** domina a un solo corte reciente (@sec-validacion-cruzada).\n- La estrategia recursiva **no** se degrada más que la directa (@sec-prediccion).\n- El boosting **no** le gana al naive estacional en series cortas (@sec-modelos-basicos).\n- Los intervalos de predicción **no** cubren lo que prometen, desde el primer paso\n  (@sec-bootstrapping).\n- El índice de complejidad predice la dificultad de una serie pero **no** cuál método la gana\n  (@sec-seleccion-escala).\n- El meta-modelo que aprende a elegir **no** generaliza a una frecuencia que no vio\n  (@sec-donde-funciona-seleccion).\n\nNinguno de esos resultados es un teorema: son mediciones sobre M4, y el @sec-los-datos explicó por\nqué M4 no es una muestra del mundo. Lo que sí es general es el procedimiento —medir antes de creer,\ny publicar el número que salió— y el libro está armado para que rehacer cualquiera de esas\nmediciones sea cuestión de cambiar una celda.\n\nDe lo que falta, tres cosas quedan explícitamente sin resolver.\n\n**El enfoque global no está demostrado acá.** La @sec-modelo-global lo explica: un catálogo de 35 series\ncuradas no puede mostrar la ventaja de entrenar un modelo sobre miles. La tesis lo midió y este\nlibro lo cita, pero no lo ejecuta.\n\n**Las redes profundas se citan, no se corren.** Es una consecuencia de la decisión de que todo\ncompile en el navegador, y la @sec-entorno dice cómo salirse de ella.\n\n**Y la aplicación es otro proyecto.** Lo que este capítulo midió son sus cimientos: la cota de la\n@eq-cota-condicional, el ensamble de la @eq-ensamble-semillas, la selección condicionada a la\nestructura de la serie del @sec-seleccion-escala, el presupuesto de latencia y la validación de\nentrada. Lo que falta es todo lo demás, que es mucho.\n\nSi algo de todo esto te resultó útil, la parte útil no son los métodos: es la costumbre de no\npublicar un número sin haberlo medido, y de publicar el que salió.\n\n## Ejercicios\n\nLas soluciones están en la @sec-soluciones-25.\n\n**1.** La @tbl-cota-condicional usa el umbral $F_T > 0{,}8$ de la @eq-cota-condicional. Bárrelo\nentre 0 y 1 y mira cómo cambian el sMAPE medio y el peor daño. ¿Hay un umbral mejor, y qué tan\nsensible es el resultado a esa elección?\n\n**2.** La cota se midió con Holt, que se desbarranca fácil. Repítela con el ARIMA(1,1,1) y con la\nestrategia recursiva de Ridge del @sec-modelos-basicos. ¿La cota sigue ganando cuando el método base\nno produce absurdos?\n\n**3.** La @tbl-cota-intervalo mide cobertura y ancho. Agrega una tercera medida: la proporción del\nancho del intervalo que cae en la región imposible. ¿Cuánto del intervalo del 95 % es, literalmente,\nespacio desperdiciado?\n\n**4.** Agrega tres casos a la @tbl-limites: una serie con un solo punto, una serie con todos los\nvalores negativos y una serie donde el último valor es cero. Clasifica cada resultado en falla\nruidosa, silenciosa o sin aviso.\n\n**5.** La @tbl-almacenamiento mide Ridge, boosting y un perceptrón. Agrega el bosque aleatorio y\nextra trees del @sec-modelos-basicos, que fueron los que mejor midieron ahí, y calcula el\nalmacenamiento total para las 99.935 series con la estrategia que el @sec-prediccion recomendó.\n\n**6.** La @tbl-antiguedad congela el ajuste y lo compara con reajustar en cada origen. Agrega una\ntercera política —reajustar cada dos horizontes— y compara las tres por error y por cantidad de\najustes. ¿Dónde está el punto en que reajustar más seguido deja de pagar?\n\n## Referencias {.unnumbered}\n\n::: {#refs}\n:::\n\n",
    "supporting": [
      "25-produccion_files/figure-html"
    ],
    "filters": [],
    "includes": {
      "include-in-header": [
        "<script src=\"https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js\" integrity=\"sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx\" crossorigin=\"anonymous\"></script>\n<script src=\"https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js\" integrity=\"sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2\" crossorigin=\"anonymous\" data-relocate-top=\"true\"></script>\n<script type=\"application/javascript\">define('jquery', [],function() {return window.jQuery;})</script>\n"
      ]
    }
  }
}